# Generated by Django 4.0.5 on 2022-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_myuser_user_myuser_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile_number',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
