# Generated by Django 4.0.5 on 2022-06-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_myuser_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('Categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='myuser',
        ),
    ]
