# Generated by Django 4.0.5 on 2022-06-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_expense_currencytype_expense_currencytype_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='CurrencyType_currency',
        ),
        migrations.AlterField(
            model_name='expense',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='CurrencyType',
            field=models.CharField(default='INR', max_length=500),
        ),
    ]
